name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libev-dev libcurl4-gnutls-dev
      
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install libev curl
      
      - name: Use dune
        uses: ocaml-dune/setup-dune@v0
      
      - name: Build
        run: dune build
      
      - name: Run tests
        run: dune runtest
      
      - name: Check formatting
        run: dune build @fmt
